name: Run Cart Tests
on: push
jobs:
    run-cart-tests:
        runs-on: ubuntu-latest
        env:
          DATABASE_USER: ${{ secrets.DB_USER }}
          DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DB_DATABASE_NAME }}
          DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:5432/${{ secrets.DB_DATABASE_NAME }}
        services:
          postgres:
            image: postgres:13
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: ${{ env.DATABASE_NAME }}
            ports:
              - 5432:5432
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run cart tests with PostgresSQL
              env:
                DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:5432/${{ secrets.DB_DATABASE_NAME }}
              run: npx mocha tests/cartApiTest.js
