name: Run Cart Tests
on: push
jobs:
    run-cart-tests:
        runs-on: ubuntu-latest
        env:
          DATABASE_USER: 'otherPostgres'
        services:
          postgres:
            image: postgres:13
            env:
              POSTGRES_USER: 'postgres'
              POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
              POSTGRES_DB: ${{ secrets.DB_DATABASE_NAME }}
            ports:
              - 5432:5432
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: check env values
              run: | 
                echo "${{ env.DATABASE_USER }} ${{ secrets.DB_PASSWORD }} ${{ secrets.DB_DATABASE_NAME }}"
            # - name: Run cart tests with PostgresSQL
            #   env:
            #     POSTGRES_USER: ${{ env.POSTGRES_USER }}
            #     POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
            #     POSTGRES_DB: ${{ env.POSTGRES_DB }}
            #     POSTGRES_HOST: localhost
            #     POSTGRES_PORT: 5432
            #   run: npx mocha tests/cartApiTest.js
